### ISSUE TITLE
add distro names

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#235] opened 2018-03-19 11:50 UTC
The quick setup page expects me to identify my distro purely by its logo. I'm not sure that is easy for everybody. Showing the name somehow might help.

**Comment by jimmac** [comment] 2018-03-19 15:04
This is a duplicate of https://github.com/flatpak/flatpak.github.io/issues/236

**Closed by jimmac** 2018-03-19 15:04 UTC
