### ISSUE TITLE
Website needs HTTPs

### ISSUE THREAD

**Issue by johnnyasantoss** [flatpak/flatpak.github.io#197] opened 2017-10-14 14:08 UTC
Hello!

Why the Flatpak's website is using http and don't have a https version?
I mean, there's links to install applications through `.flatpakref` this shouldn't be using a insecure connection.

**Comment by jean-lourenco** [comment] 2017-10-14 14:15
Yep, this is a must.
If the site is hosted on github pages with a custom domain, it's still possible to add https using a cloudflare free account.

**Comment by mwleeds** [comment] 2017-10-14 17:47
This is a duplicate of #74

**Closed** 2017-10-14 19:18 UTC
Labels: duplicate
