### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by haecker-felix** [flatpak/flatpak.github.io#172] opened 2017-05-14 14:46 UTC
http://flatpak.org/apps.html

Clicking on "Recipes":

404 https://git.gnome.org/browse/recipes/plain/flatpak/gnome-recipes.flatpakref?h=stable not found.

**Comment by jimmac** [comment] 2017-05-14 14:51
Duplicate of Issue #171

**Closed by jimmac** 2017-05-14 14:51 UTC
